---
name: Quark
author: bitrule
version: "1.0"
api: 5.0.0
main: bitrule\quark\Quark
softdepend:
- Gorufus
permissions:
  quark.command.group:
    description: Allows the player to use the /quark command
    default: true
  quark.command.group.create:
    description: Allows the player to use the /quark create command
    default: true
  quark.command.group.suffix:
    description: Allows the player to use the /quark create command
    default: true
  quark.command.group.prefix:
    description: Allows the player to use the /quark create command
    default: true
  quark.command.group.display:
    description: Allows the player to use the /quark create command
    default: true
  quark.command.group.priority:
    description: Allows the player to use the /quark create command
    default: true
  quark.command.grant:
    description: Allows the player to use the /quark create command
    default: true
...
