---
name: Quark
author: bitrule
version: "1.0"
api: 5.0.0
main: bitrule\quark\Quark
permissions:
  quark.command.group:
    description: Allows the player to use the /quark command
    default: true
  quark.command.group.create:
    description: Allows the player to use the /quark create command
    default: true
...
